[FEAT] Layout ( Header, Footer) 컴포넌트 제작
prgrms-web-devcourse-final-project/WEB1_1_ZeroOne_FE pull request #22
Opened 2024-11-22 17:54 UTC by csk6314

## 📌 관련 이슈

- Closes #20 

<br/>

## 💭 작업 내용

<br/>

## 🤔 참고 사항

- [ ]

<br/>

## 📸 스크린샷

2024-11-23 07:34 UTC, joarthvr approved these changes

2024-11-23 07:34 UTC, joarthvr commented
라이트 하우스가 자꾸 스킵되네요 이거도 확인 후 수정해보겠습니다..

2024-11-23 15:47 UTC, he2e2 requested changes
컴포넌트 파일을 `Button/index.ts`, `Button/index.module.scss` 로 할 지, `Button/Button.tsx`, `Button/Button.module.scss`로 할 지 같이 고민해보면 좋을 것 같습니다👍

아 그리고 저 test 시, 에러 나는 거 한 번만 확인 부탁드립니당

2024-11-23 15:47 UTC, he2e2 commented on src/widgets/Layout/ui/Footer/index.tsx
> +    <div className={styles.footer}>
footer 태그를 쓰는 게 조금 더 의미 있을 것 같습니다 ( Header 컴포넌트도 마찬가지로 header 태그를 쓸 수 있을 것 같아요!) 👀

2024-11-24 07:52 UTC, csk6314 commented on src/widgets/Layout/ui/Footer/index.tsx
> +    <div className={styles.footer}>
아 그러네요!
header랑 footer 태그로 전부 수정하겠습니다 ㅎ
그리고  컴포넌트 파일은 저도 계속 고민했는데, index로 하는게 import 경로에 깔끔하게 나오긴 하더라구요.
근데 또  ui에 index.ts써서 내보낼거면 그냥 Button.tsx로 해도 상관 없을 것 같습니다!

2024-11-24 08:56 UTC, csk6314 commented
테스트 문제 해결했습니다.
1. identity-obj-proxy 테스트 플러그인 설치 안되있던거 설치했습니다.
2. 테스트시 SVG 모킹 작업하게 끔 설정해놨습니다.

2024-11-24 09:27 UTC, csk6314 commented
파일이름 index.tsx -> Component.tsx로 모두 변경하였습니다

2024-11-24 10:13 UTC, he2e2 approved these changes
LGTM🔥

2024-11-24 10:14 UTC, merged